import type { TechnologyCategory } from '@/types'

export interface TechnologySeed {
  slug: string
  name: string
  description: string
  category: TechnologyCategory
  ecosystem: string | null
  website_url: string | null
  github_repo: string | null
  npm_package: string | null
  pypi_package: string | null
  crates_package: string | null
  stackoverflow_tag: string
  subreddit: string | null
  devto_tag: string | null
  aliases: string[]
  color: string
  first_appeared: number | null
  maintained_by: string | null
}

export const TECHNOLOGIES: TechnologySeed[] = [
  // ============================================
  // LANGUAGES (20)
  // ============================================
  {
    slug: 'javascript',
    name: 'JavaScript',
    description: 'High-level, dynamic programming language for the web',
    category: 'language',
    ecosystem: 'javascript',
    website_url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'javascript',
    subreddit: 'javascript',
    devto_tag: 'javascript',
    aliases: ['js', 'ecmascript', 'es6'],
    color: '#F7DF1E',
    first_appeared: 1995,
    maintained_by: 'ECMA International',
  },
  {
    slug: 'typescript',
    name: 'TypeScript',
    description: 'Typed superset of JavaScript that compiles to plain JS',
    category: 'language',
    ecosystem: 'javascript',
    website_url: 'https://www.typescriptlang.org',
    github_repo: 'microsoft/TypeScript',
    npm_package: 'typescript',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'typescript',
    subreddit: 'typescript',
    devto_tag: 'typescript',
    aliases: ['ts'],
    color: '#3178C6',
    first_appeared: 2012,
    maintained_by: 'Microsoft',
  },
  {
    slug: 'python',
    name: 'Python',
    description: 'General-purpose programming language emphasizing readability',
    category: 'language',
    ecosystem: 'python',
    website_url: 'https://www.python.org',
    github_repo: 'python/cpython',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'python',
    subreddit: 'python',
    devto_tag: 'python',
    aliases: ['py', 'python3'],
    color: '#3776AB',
    first_appeared: 1991,
    maintained_by: 'Python Software Foundation',
  },
  {
    slug: 'rust',
    name: 'Rust',
    description: 'Systems programming language focused on safety and performance',
    category: 'language',
    ecosystem: 'rust',
    website_url: 'https://www.rust-lang.org',
    github_repo: 'rust-lang/rust',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'rust',
    subreddit: 'rust',
    devto_tag: 'rust',
    aliases: ['rustlang'],
    color: '#DEA584',
    first_appeared: 2010,
    maintained_by: 'Rust Foundation',
  },
  {
    slug: 'go',
    name: 'Go',
    description: 'Statically typed, compiled language designed at Google',
    category: 'language',
    ecosystem: 'go',
    website_url: 'https://go.dev',
    github_repo: 'golang/go',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'go',
    subreddit: 'golang',
    devto_tag: 'go',
    aliases: ['golang'],
    color: '#00ADD8',
    first_appeared: 2009,
    maintained_by: 'Google',
  },
  {
    slug: 'java',
    name: 'Java',
    description: 'Object-oriented programming language for enterprise applications',
    category: 'language',
    ecosystem: 'java',
    website_url: 'https://www.java.com',
    github_repo: 'openjdk/jdk',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'java',
    subreddit: 'java',
    devto_tag: 'java',
    aliases: ['jdk', 'jvm'],
    color: '#ED8B00',
    first_appeared: 1995,
    maintained_by: 'Oracle',
  },
  {
    slug: 'csharp',
    name: 'C#',
    description: 'Modern object-oriented language for the .NET platform',
    category: 'language',
    ecosystem: 'dotnet',
    website_url: 'https://learn.microsoft.com/en-us/dotnet/csharp/',
    github_repo: 'dotnet/csharplang',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'c%23',
    subreddit: 'csharp',
    devto_tag: 'csharp',
    aliases: ['c-sharp', 'dotnet'],
    color: '#512BD4',
    first_appeared: 2000,
    maintained_by: 'Microsoft',
  },
  {
    slug: 'cpp',
    name: 'C++',
    description: 'General-purpose language with object-oriented and generic features',
    category: 'language',
    ecosystem: null,
    website_url: 'https://isocpp.org',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'c%2B%2B',
    subreddit: 'cpp',
    devto_tag: 'cpp',
    aliases: ['cplusplus'],
    color: '#00599C',
    first_appeared: 1985,
    maintained_by: 'ISO C++ Committee',
  },
  {
    slug: 'c',
    name: 'C',
    description: 'Low-level systems programming language',
    category: 'language',
    ecosystem: null,
    website_url: null,
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'c',
    subreddit: 'C_Programming',
    devto_tag: 'c',
    aliases: ['clang'],
    color: '#A8B9CC',
    first_appeared: 1972,
    maintained_by: 'ISO C Committee',
  },
  {
    slug: 'swift',
    name: 'Swift',
    description: 'General-purpose language for Apple platforms',
    category: 'language',
    ecosystem: null,
    website_url: 'https://www.swift.org',
    github_repo: 'swiftlang/swift',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'swift',
    subreddit: 'swift',
    devto_tag: 'swift',
    aliases: ['swiftlang'],
    color: '#F05138',
    first_appeared: 2014,
    maintained_by: 'Apple',
  },
  {
    slug: 'kotlin',
    name: 'Kotlin',
    description: 'Modern language for JVM, Android, and multiplatform development',
    category: 'language',
    ecosystem: 'java',
    website_url: 'https://kotlinlang.org',
    github_repo: 'JetBrains/kotlin',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'kotlin',
    subreddit: 'Kotlin',
    devto_tag: 'kotlin',
    aliases: ['kt'],
    color: '#7F52FF',
    first_appeared: 2011,
    maintained_by: 'JetBrains',
  },
  {
    slug: 'ruby',
    name: 'Ruby',
    description: 'Dynamic language designed for developer happiness',
    category: 'language',
    ecosystem: 'ruby',
    website_url: 'https://www.ruby-lang.org',
    github_repo: 'ruby/ruby',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'ruby',
    subreddit: 'ruby',
    devto_tag: 'ruby',
    aliases: ['rb'],
    color: '#CC342D',
    first_appeared: 1995,
    maintained_by: 'Community',
  },
  {
    slug: 'php',
    name: 'PHP',
    description: 'Server-side scripting language for web development',
    category: 'language',
    ecosystem: 'php',
    website_url: 'https://www.php.net',
    github_repo: 'php/php-src',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'php',
    subreddit: 'PHP',
    devto_tag: 'php',
    aliases: [],
    color: '#777BB4',
    first_appeared: 1995,
    maintained_by: 'Community',
  },
  {
    slug: 'dart',
    name: 'Dart',
    description: 'Client-optimized language for fast apps on any platform',
    category: 'language',
    ecosystem: 'dart',
    website_url: 'https://dart.dev',
    github_repo: 'dart-lang/sdk',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'dart',
    subreddit: 'dartlang',
    devto_tag: 'dart',
    aliases: ['dartlang'],
    color: '#0175C2',
    first_appeared: 2011,
    maintained_by: 'Google',
  },
  {
    slug: 'elixir',
    name: 'Elixir',
    description: 'Functional language for scalable and maintainable applications',
    category: 'language',
    ecosystem: 'elixir',
    website_url: 'https://elixir-lang.org',
    github_repo: 'elixir-lang/elixir',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'elixir',
    subreddit: 'elixir',
    devto_tag: 'elixir',
    aliases: [],
    color: '#6E4A7E',
    first_appeared: 2012,
    maintained_by: 'Community',
  },
  {
    slug: 'scala',
    name: 'Scala',
    description: 'Language combining object-oriented and functional programming',
    category: 'language',
    ecosystem: 'java',
    website_url: 'https://www.scala-lang.org',
    github_repo: 'scala/scala',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'scala',
    subreddit: 'scala',
    devto_tag: 'scala',
    aliases: [],
    color: '#DC322F',
    first_appeared: 2004,
    maintained_by: 'EPFL / Lightbend',
  },
  {
    slug: 'zig',
    name: 'Zig',
    description: 'Systems language designed as a better C',
    category: 'language',
    ecosystem: null,
    website_url: 'https://ziglang.org',
    github_repo: 'ziglang/zig',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'zig',
    subreddit: 'Zig',
    devto_tag: 'zig',
    aliases: ['ziglang'],
    color: '#F7A41D',
    first_appeared: 2016,
    maintained_by: 'Zig Software Foundation',
  },
  {
    slug: 'lua',
    name: 'Lua',
    description: 'Lightweight embeddable scripting language',
    category: 'language',
    ecosystem: null,
    website_url: 'https://www.lua.org',
    github_repo: 'lua/lua',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'lua',
    subreddit: 'lua',
    devto_tag: 'lua',
    aliases: [],
    color: '#7373CC',
    first_appeared: 1993,
    maintained_by: 'PUC-Rio',
  },
  {
    slug: 'r',
    name: 'R',
    description: 'Language for statistical computing and graphics',
    category: 'language',
    ecosystem: null,
    website_url: 'https://www.r-project.org',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'r',
    subreddit: 'rlanguage',
    devto_tag: 'r',
    aliases: ['rlang', 'rstats'],
    color: '#276DC3',
    first_appeared: 1993,
    maintained_by: 'R Foundation',
  },
  {
    slug: 'haskell',
    name: 'Haskell',
    description: 'Purely functional programming language',
    category: 'language',
    ecosystem: null,
    website_url: 'https://www.haskell.org',
    github_repo: 'ghc/ghc',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'haskell',
    subreddit: 'haskell',
    devto_tag: 'haskell',
    aliases: ['ghc'],
    color: '#5D4F85',
    first_appeared: 1990,
    maintained_by: 'Community',
  },

  // ============================================
  // FRONTEND FRAMEWORKS (15)
  // ============================================
  {
    slug: 'react',
    name: 'React',
    description: 'JavaScript library for building user interfaces',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://react.dev',
    github_repo: 'facebook/react',
    npm_package: 'react',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'reactjs',
    subreddit: 'reactjs',
    devto_tag: 'react',
    aliases: ['reactjs', 'react.js'],
    color: '#61DAFB',
    first_appeared: 2013,
    maintained_by: 'Meta',
  },
  {
    slug: 'vue',
    name: 'Vue.js',
    description: 'Progressive framework for building user interfaces',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://vuejs.org',
    github_repo: 'vuejs/core',
    npm_package: 'vue',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'vue.js',
    subreddit: 'vuejs',
    devto_tag: 'vue',
    aliases: ['vuejs', 'vue.js'],
    color: '#4FC08D',
    first_appeared: 2014,
    maintained_by: 'Community',
  },
  {
    slug: 'angular',
    name: 'Angular',
    description: 'Platform for building mobile and desktop web apps',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://angular.dev',
    github_repo: 'angular/angular',
    npm_package: '@angular/core',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'angular',
    subreddit: 'angular',
    devto_tag: 'angular',
    aliases: ['angular2', 'angularjs'],
    color: '#DD0031',
    first_appeared: 2016,
    maintained_by: 'Google',
  },
  {
    slug: 'svelte',
    name: 'Svelte',
    description: 'Compiler that generates minimal framework-less JavaScript',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://svelte.dev',
    github_repo: 'sveltejs/svelte',
    npm_package: 'svelte',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'svelte',
    subreddit: 'sveltejs',
    devto_tag: 'svelte',
    aliases: ['sveltejs'],
    color: '#FF3E00',
    first_appeared: 2016,
    maintained_by: 'Community',
  },
  {
    slug: 'nextjs',
    name: 'Next.js',
    description: 'React framework for production with SSR and SSG',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://nextjs.org',
    github_repo: 'vercel/next.js',
    npm_package: 'next',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'next.js',
    subreddit: 'nextjs',
    devto_tag: 'nextjs',
    aliases: ['next', 'next.js'],
    color: '#AAAAAA',
    first_appeared: 2016,
    maintained_by: 'Vercel',
  },
  {
    slug: 'nuxt',
    name: 'Nuxt',
    description: 'Vue framework for server-side rendering and static sites',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://nuxt.com',
    github_repo: 'nuxt/nuxt',
    npm_package: 'nuxt',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'nuxt.js',
    subreddit: 'nuxt',
    devto_tag: 'nuxt',
    aliases: ['nuxtjs', 'nuxt.js'],
    color: '#00DC82',
    first_appeared: 2016,
    maintained_by: 'Community',
  },
  {
    slug: 'remix',
    name: 'Remix',
    description: 'Full-stack React framework focused on web standards',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://remix.run',
    github_repo: 'remix-run/remix',
    npm_package: '@remix-run/react',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'remix',
    subreddit: 'remix_run',
    devto_tag: 'remix',
    aliases: ['remix-run'],
    color: '#7C4DFF',
    first_appeared: 2021,
    maintained_by: 'Shopify',
  },
  {
    slug: 'astro',
    name: 'Astro',
    description: 'Web framework for content-driven websites with islands architecture',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://astro.build',
    github_repo: 'withastro/astro',
    npm_package: 'astro',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'astro',
    subreddit: 'astro',
    devto_tag: 'astro',
    aliases: ['astrojs'],
    color: '#FF5D01',
    first_appeared: 2021,
    maintained_by: 'Community',
  },
  {
    slug: 'solidjs',
    name: 'Solid.js',
    description: 'Declarative reactive JavaScript library for building UIs',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://www.solidjs.com',
    github_repo: 'solidjs/solid',
    npm_package: 'solid-js',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'solidjs',
    subreddit: 'solidjs',
    devto_tag: 'solidjs',
    aliases: ['solid', 'solid-js'],
    color: '#4D8FCC',
    first_appeared: 2018,
    maintained_by: 'Community',
  },
  {
    slug: 'qwik',
    name: 'Qwik',
    description: 'Framework for instantly-interactive web apps with resumability',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://qwik.dev',
    github_repo: 'QwikDev/qwik',
    npm_package: '@builder.io/qwik',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'qwik',
    subreddit: 'qwik',
    devto_tag: 'qwik',
    aliases: ['qwikdev'],
    color: '#18B6F6',
    first_appeared: 2022,
    maintained_by: 'Builder.io',
  },
  {
    slug: 'htmx',
    name: 'htmx',
    description: 'Access modern browser features directly from HTML',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://htmx.org',
    github_repo: 'bigskysoftware/htmx',
    npm_package: 'htmx.org',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'htmx',
    subreddit: 'htmx',
    devto_tag: 'htmx',
    aliases: [],
    color: '#3366CC',
    first_appeared: 2020,
    maintained_by: 'Community',
  },
  {
    slug: 'tailwindcss',
    name: 'Tailwind CSS',
    description: 'Utility-first CSS framework for rapid UI development',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://tailwindcss.com',
    github_repo: 'tailwindlabs/tailwindcss',
    npm_package: 'tailwindcss',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'tailwind-css',
    subreddit: 'tailwindcss',
    devto_tag: 'tailwindcss',
    aliases: ['tailwind'],
    color: '#06B6D4',
    first_appeared: 2017,
    maintained_by: 'Tailwind Labs',
  },
  {
    slug: 'bootstrap',
    name: 'Bootstrap',
    description: 'Popular HTML, CSS, and JS framework for responsive sites',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://getbootstrap.com',
    github_repo: 'twbs/bootstrap',
    npm_package: 'bootstrap',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'bootstrap',
    subreddit: 'bootstrap',
    devto_tag: 'bootstrap',
    aliases: ['bootstrap5', 'twitter-bootstrap'],
    color: '#7952B3',
    first_appeared: 2011,
    maintained_by: 'Community',
  },
  {
    slug: 'jquery',
    name: 'jQuery',
    description: 'Fast, small, feature-rich JavaScript library',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://jquery.com',
    github_repo: 'jquery/jquery',
    npm_package: 'jquery',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'jquery',
    subreddit: 'jquery',
    devto_tag: 'jquery',
    aliases: ['jq'],
    color: '#0769AD',
    first_appeared: 2006,
    maintained_by: 'OpenJS Foundation',
  },
  {
    slug: 'lit',
    name: 'Lit',
    description: 'Simple library for building fast web components',
    category: 'frontend',
    ecosystem: 'javascript',
    website_url: 'https://lit.dev',
    github_repo: 'lit/lit',
    npm_package: 'lit',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'lit',
    subreddit: null,
    devto_tag: 'lit',
    aliases: ['lit-element', 'lit-html'],
    color: '#324FFF',
    first_appeared: 2018,
    maintained_by: 'Google',
  },

  // ============================================
  // BACKEND FRAMEWORKS (15)
  // ============================================
  {
    slug: 'nodejs',
    name: 'Node.js',
    description: 'JavaScript runtime built on V8 for server-side applications',
    category: 'backend',
    ecosystem: 'javascript',
    website_url: 'https://nodejs.org',
    github_repo: 'nodejs/node',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'node.js',
    subreddit: 'node',
    devto_tag: 'node',
    aliases: ['node', 'node.js'],
    color: '#339933',
    first_appeared: 2009,
    maintained_by: 'OpenJS Foundation',
  },
  {
    slug: 'express',
    name: 'Express',
    description: 'Minimal and flexible Node.js web application framework',
    category: 'backend',
    ecosystem: 'javascript',
    website_url: 'https://expressjs.com',
    github_repo: 'expressjs/express',
    npm_package: 'express',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'express',
    subreddit: 'expressjs',
    devto_tag: 'express',
    aliases: ['expressjs'],
    color: '#999999',
    first_appeared: 2010,
    maintained_by: 'OpenJS Foundation',
  },
  {
    slug: 'fastify',
    name: 'Fastify',
    description: 'Fast and low overhead Node.js web framework',
    category: 'backend',
    ecosystem: 'javascript',
    website_url: 'https://fastify.dev',
    github_repo: 'fastify/fastify',
    npm_package: 'fastify',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'fastify',
    subreddit: null,
    devto_tag: 'fastify',
    aliases: [],
    color: '#20C6A0',
    first_appeared: 2016,
    maintained_by: 'Community',
  },
  {
    slug: 'django',
    name: 'Django',
    description: 'High-level Python web framework for rapid development',
    category: 'backend',
    ecosystem: 'python',
    website_url: 'https://www.djangoproject.com',
    github_repo: 'django/django',
    npm_package: null,
    pypi_package: 'django',
    crates_package: null,
    stackoverflow_tag: 'django',
    subreddit: 'django',
    devto_tag: 'django',
    aliases: ['djangoproject'],
    color: '#44B78B',
    first_appeared: 2005,
    maintained_by: 'Django Software Foundation',
  },
  {
    slug: 'flask',
    name: 'Flask',
    description: 'Lightweight Python WSGI web application framework',
    category: 'backend',
    ecosystem: 'python',
    website_url: 'https://flask.palletsprojects.com',
    github_repo: 'pallets/flask',
    npm_package: null,
    pypi_package: 'flask',
    crates_package: null,
    stackoverflow_tag: 'flask',
    subreddit: 'flask',
    devto_tag: 'flask',
    aliases: [],
    color: '#999999',
    first_appeared: 2010,
    maintained_by: 'Pallets',
  },
  {
    slug: 'fastapi',
    name: 'FastAPI',
    description: 'Modern, fast Python web framework for building APIs',
    category: 'backend',
    ecosystem: 'python',
    website_url: 'https://fastapi.tiangolo.com',
    github_repo: 'fastapi/fastapi',
    npm_package: null,
    pypi_package: 'fastapi',
    crates_package: null,
    stackoverflow_tag: 'fastapi',
    subreddit: 'fastapi',
    devto_tag: 'fastapi',
    aliases: [],
    color: '#009688',
    first_appeared: 2018,
    maintained_by: 'Community',
  },
  {
    slug: 'spring-boot',
    name: 'Spring Boot',
    description: 'Java framework for creating production-grade applications',
    category: 'backend',
    ecosystem: 'java',
    website_url: 'https://spring.io/projects/spring-boot',
    github_repo: 'spring-projects/spring-boot',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'spring-boot',
    subreddit: 'SpringBoot',
    devto_tag: 'springboot',
    aliases: ['spring', 'springboot'],
    color: '#6DB33F',
    first_appeared: 2014,
    maintained_by: 'VMware',
  },
  {
    slug: 'dotnet',
    name: 'ASP.NET Core',
    description: 'Cross-platform framework for building web apps with .NET',
    category: 'backend',
    ecosystem: 'dotnet',
    website_url: 'https://dotnet.microsoft.com/en-us/apps/aspnet',
    github_repo: 'dotnet/aspnetcore',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'asp.net-core',
    subreddit: 'dotnet',
    devto_tag: 'dotnet',
    aliases: ['aspnet', 'asp.net'],
    color: '#512BD4',
    first_appeared: 2016,
    maintained_by: 'Microsoft',
  },
  {
    slug: 'rails',
    name: 'Ruby on Rails',
    description: 'Server-side web application framework written in Ruby',
    category: 'backend',
    ecosystem: 'ruby',
    website_url: 'https://rubyonrails.org',
    github_repo: 'rails/rails',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'ruby-on-rails',
    subreddit: 'rails',
    devto_tag: 'rails',
    aliases: ['ror', 'ruby-on-rails'],
    color: '#CC0000',
    first_appeared: 2005,
    maintained_by: 'Community',
  },
  {
    slug: 'laravel',
    name: 'Laravel',
    description: 'PHP framework for web artisans with expressive syntax',
    category: 'backend',
    ecosystem: 'php',
    website_url: 'https://laravel.com',
    github_repo: 'laravel/laravel',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'laravel',
    subreddit: 'laravel',
    devto_tag: 'laravel',
    aliases: [],
    color: '#FF2D20',
    first_appeared: 2011,
    maintained_by: 'Community',
  },
  {
    slug: 'phoenix',
    name: 'Phoenix',
    description: 'Web framework for Elixir with real-time capabilities',
    category: 'backend',
    ecosystem: 'elixir',
    website_url: 'https://www.phoenixframework.org',
    github_repo: 'phoenixframework/phoenix',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'phoenix-framework',
    subreddit: 'elixir',
    devto_tag: 'phoenix',
    aliases: ['phoenix-framework'],
    color: '#FD4F00',
    first_appeared: 2014,
    maintained_by: 'Community',
  },
  {
    slug: 'gin',
    name: 'Gin',
    description: 'HTTP web framework written in Go with high performance',
    category: 'backend',
    ecosystem: 'go',
    website_url: 'https://gin-gonic.com',
    github_repo: 'gin-gonic/gin',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'go-gin',
    subreddit: 'golang',
    devto_tag: 'gin',
    aliases: ['gin-gonic'],
    color: '#00ADD8',
    first_appeared: 2014,
    maintained_by: 'Community',
  },
  {
    slug: 'fiber',
    name: 'Fiber',
    description: 'Express-inspired Go web framework built on Fasthttp',
    category: 'backend',
    ecosystem: 'go',
    website_url: 'https://gofiber.io',
    github_repo: 'gofiber/fiber',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'gofiber',
    subreddit: 'golang',
    devto_tag: 'fiber',
    aliases: ['gofiber'],
    color: '#00ACD7',
    first_appeared: 2020,
    maintained_by: 'Community',
  },
  {
    slug: 'nestjs',
    name: 'NestJS',
    description: 'Progressive Node.js framework for server-side applications',
    category: 'backend',
    ecosystem: 'javascript',
    website_url: 'https://nestjs.com',
    github_repo: 'nestjs/nest',
    npm_package: '@nestjs/core',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'nestjs',
    subreddit: 'nestjs',
    devto_tag: 'nestjs',
    aliases: ['nest'],
    color: '#E0234E',
    first_appeared: 2017,
    maintained_by: 'Community',
  },
  {
    slug: 'hono',
    name: 'Hono',
    description: 'Ultrafast web framework for the Edge',
    category: 'backend',
    ecosystem: 'javascript',
    website_url: 'https://hono.dev',
    github_repo: 'honojs/hono',
    npm_package: 'hono',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'hono',
    subreddit: null,
    devto_tag: 'hono',
    aliases: ['honojs'],
    color: '#FF6600',
    first_appeared: 2022,
    maintained_by: 'Community',
  },

  // ============================================
  // DATABASES (15)
  // ============================================
  {
    slug: 'postgresql',
    name: 'PostgreSQL',
    description: 'Powerful open-source relational database system',
    category: 'database',
    ecosystem: null,
    website_url: 'https://www.postgresql.org',
    github_repo: 'postgres/postgres',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'postgresql',
    subreddit: 'postgresql',
    devto_tag: 'postgres',
    aliases: ['postgres', 'pg'],
    color: '#4169E1',
    first_appeared: 1996,
    maintained_by: 'Community',
  },
  {
    slug: 'mysql',
    name: 'MySQL',
    description: 'Open-source relational database management system',
    category: 'database',
    ecosystem: null,
    website_url: 'https://www.mysql.com',
    github_repo: 'mysql/mysql-server',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'mysql',
    subreddit: 'mysql',
    devto_tag: 'mysql',
    aliases: ['mariadb'],
    color: '#4479A1',
    first_appeared: 1995,
    maintained_by: 'Oracle',
  },
  {
    slug: 'mongodb',
    name: 'MongoDB',
    description: 'Document-oriented NoSQL database',
    category: 'database',
    ecosystem: null,
    website_url: 'https://www.mongodb.com',
    github_repo: 'mongodb/mongo',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'mongodb',
    subreddit: 'mongodb',
    devto_tag: 'mongodb',
    aliases: ['mongo'],
    color: '#47A248',
    first_appeared: 2009,
    maintained_by: 'MongoDB Inc.',
  },
  {
    slug: 'redis',
    name: 'Redis',
    description: 'In-memory data structure store used as database and cache',
    category: 'database',
    ecosystem: null,
    website_url: 'https://redis.io',
    github_repo: 'redis/redis',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'redis',
    subreddit: 'redis',
    devto_tag: 'redis',
    aliases: [],
    color: '#DC382D',
    first_appeared: 2009,
    maintained_by: 'Redis Ltd.',
  },
  {
    slug: 'sqlite',
    name: 'SQLite',
    description: 'Self-contained serverless SQL database engine',
    category: 'database',
    ecosystem: null,
    website_url: 'https://www.sqlite.org',
    github_repo: 'sqlite/sqlite',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'sqlite',
    subreddit: 'sqlite',
    devto_tag: 'sqlite',
    aliases: ['sqlite3'],
    color: '#0099BB',
    first_appeared: 2000,
    maintained_by: 'D. Richard Hipp',
  },
  {
    slug: 'cassandra',
    name: 'Cassandra',
    description: 'Distributed NoSQL database for high availability',
    category: 'database',
    ecosystem: null,
    website_url: 'https://cassandra.apache.org',
    github_repo: 'apache/cassandra',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'cassandra',
    subreddit: 'cassandra',
    devto_tag: 'cassandra',
    aliases: ['apache-cassandra'],
    color: '#1287B1',
    first_appeared: 2008,
    maintained_by: 'Apache Software Foundation',
  },
  {
    slug: 'dynamodb',
    name: 'DynamoDB',
    description: 'Fully managed NoSQL database service by AWS',
    category: 'database',
    ecosystem: null,
    website_url: 'https://aws.amazon.com/dynamodb/',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'amazon-dynamodb',
    subreddit: 'aws',
    devto_tag: 'dynamodb',
    aliases: ['dynamo'],
    color: '#4053D6',
    first_appeared: 2012,
    maintained_by: 'Amazon',
  },
  {
    slug: 'supabase',
    name: 'Supabase',
    description: 'Open-source Firebase alternative with PostgreSQL',
    category: 'database',
    ecosystem: null,
    website_url: 'https://supabase.com',
    github_repo: 'supabase/supabase',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'supabase',
    subreddit: 'supabase',
    devto_tag: 'supabase',
    aliases: [],
    color: '#3FCF8E',
    first_appeared: 2020,
    maintained_by: 'Supabase Inc.',
  },
  {
    slug: 'planetscale',
    name: 'PlanetScale',
    description: 'Serverless MySQL platform with branching',
    category: 'database',
    ecosystem: null,
    website_url: 'https://planetscale.com',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'planetscale',
    subreddit: 'planetscale',
    devto_tag: 'planetscale',
    aliases: [],
    color: '#8B5CF6',
    first_appeared: 2021,
    maintained_by: 'PlanetScale Inc.',
  },
  {
    slug: 'neon',
    name: 'Neon',
    description: 'Serverless Postgres with branching and autoscaling',
    category: 'database',
    ecosystem: null,
    website_url: 'https://neon.tech',
    github_repo: 'neondatabase/neon',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'neon-database',
    subreddit: 'neon',
    devto_tag: 'neon',
    aliases: ['neondb'],
    color: '#00E699',
    first_appeared: 2022,
    maintained_by: 'Neon Inc.',
  },
  {
    slug: 'turso',
    name: 'Turso',
    description: 'Edge-hosted distributed SQLite database',
    category: 'database',
    ecosystem: null,
    website_url: 'https://turso.tech',
    github_repo: 'tursodatabase/libsql',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'turso',
    subreddit: 'turso',
    devto_tag: 'turso',
    aliases: ['libsql'],
    color: '#4FF8D2',
    first_appeared: 2022,
    maintained_by: 'Turso Inc.',
  },
  {
    slug: 'elasticsearch',
    name: 'Elasticsearch',
    description: 'Distributed search and analytics engine',
    category: 'database',
    ecosystem: null,
    website_url: 'https://www.elastic.co/elasticsearch',
    github_repo: 'elastic/elasticsearch',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'elasticsearch',
    subreddit: 'elasticsearch',
    devto_tag: 'elasticsearch',
    aliases: ['elastic', 'es'],
    color: '#00AACC',
    first_appeared: 2010,
    maintained_by: 'Elastic',
  },
  {
    slug: 'clickhouse',
    name: 'ClickHouse',
    description: 'Column-oriented OLAP database for real-time analytics',
    category: 'database',
    ecosystem: null,
    website_url: 'https://clickhouse.com',
    github_repo: 'ClickHouse/ClickHouse',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'clickhouse',
    subreddit: 'clickhouse',
    devto_tag: 'clickhouse',
    aliases: ['ch'],
    color: '#FFCC00',
    first_appeared: 2016,
    maintained_by: 'ClickHouse Inc.',
  },
  {
    slug: 'neo4j',
    name: 'Neo4j',
    description: 'Native graph database for connected data',
    category: 'database',
    ecosystem: null,
    website_url: 'https://neo4j.com',
    github_repo: 'neo4j/neo4j',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'neo4j',
    subreddit: 'neo4j',
    devto_tag: 'neo4j',
    aliases: ['neo'],
    color: '#008CC1',
    first_appeared: 2007,
    maintained_by: 'Neo4j Inc.',
  },
  {
    slug: 'dragonfly',
    name: 'Dragonfly',
    description: 'Modern in-memory datastore compatible with Redis and Memcached',
    category: 'database',
    ecosystem: null,
    website_url: 'https://www.dragonflydb.io',
    github_repo: 'dragonflydb/dragonfly',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'dragonfly',
    subreddit: 'dragonfly',
    devto_tag: 'dragonfly',
    aliases: ['dragonflydb'],
    color: '#6E9CC4',
    first_appeared: 2022,
    maintained_by: 'DragonflyDB',
  },

  // ============================================
  // DEVOPS (10)
  // ============================================
  {
    slug: 'docker',
    name: 'Docker',
    description: 'Platform for building, shipping, and running containers',
    category: 'devops',
    ecosystem: null,
    website_url: 'https://www.docker.com',
    github_repo: 'moby/moby',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'docker',
    subreddit: 'docker',
    devto_tag: 'docker',
    aliases: ['moby', 'containers'],
    color: '#2496ED',
    first_appeared: 2013,
    maintained_by: 'Docker Inc.',
  },
  {
    slug: 'kubernetes',
    name: 'Kubernetes',
    description: 'Container orchestration system for automating deployment and scaling',
    category: 'devops',
    ecosystem: null,
    website_url: 'https://kubernetes.io',
    github_repo: 'kubernetes/kubernetes',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'kubernetes',
    subreddit: 'kubernetes',
    devto_tag: 'kubernetes',
    aliases: ['k8s'],
    color: '#326CE5',
    first_appeared: 2014,
    maintained_by: 'CNCF',
  },
  {
    slug: 'terraform',
    name: 'Terraform',
    description: 'Infrastructure as code tool for provisioning cloud resources',
    category: 'devops',
    ecosystem: null,
    website_url: 'https://www.terraform.io',
    github_repo: 'hashicorp/terraform',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'terraform',
    subreddit: 'Terraform',
    devto_tag: 'terraform',
    aliases: ['tf', 'hcl'],
    color: '#7B42BC',
    first_appeared: 2014,
    maintained_by: 'HashiCorp',
  },
  {
    slug: 'github-actions',
    name: 'GitHub Actions',
    description: 'CI/CD automation platform built into GitHub',
    category: 'devops',
    ecosystem: null,
    website_url: 'https://github.com/features/actions',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'github-actions',
    subreddit: 'github',
    devto_tag: 'githubactions',
    aliases: ['gha', 'gh-actions'],
    color: '#2088FF',
    first_appeared: 2019,
    maintained_by: 'GitHub',
  },
  {
    slug: 'jenkins',
    name: 'Jenkins',
    description: 'Open-source automation server for CI/CD pipelines',
    category: 'devops',
    ecosystem: null,
    website_url: 'https://www.jenkins.io',
    github_repo: 'jenkinsci/jenkins',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'jenkins',
    subreddit: 'jenkins',
    devto_tag: 'jenkins',
    aliases: [],
    color: '#D24939',
    first_appeared: 2011,
    maintained_by: 'Community',
  },
  {
    slug: 'ansible',
    name: 'Ansible',
    description: 'Agentless IT automation tool for configuration management',
    category: 'devops',
    ecosystem: 'python',
    website_url: 'https://www.ansible.com',
    github_repo: 'ansible/ansible',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'ansible',
    subreddit: 'ansible',
    devto_tag: 'ansible',
    aliases: [],
    color: '#EE0000',
    first_appeared: 2012,
    maintained_by: 'Red Hat',
  },
  {
    slug: 'prometheus',
    name: 'Prometheus',
    description: 'Open-source monitoring and alerting toolkit',
    category: 'devops',
    ecosystem: null,
    website_url: 'https://prometheus.io',
    github_repo: 'prometheus/prometheus',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'prometheus',
    subreddit: 'PrometheusMonitoring',
    devto_tag: 'prometheus',
    aliases: ['prom'],
    color: '#E6522C',
    first_appeared: 2012,
    maintained_by: 'CNCF',
  },
  {
    slug: 'grafana',
    name: 'Grafana',
    description: 'Open-source analytics and monitoring platform',
    category: 'devops',
    ecosystem: null,
    website_url: 'https://grafana.com',
    github_repo: 'grafana/grafana',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'grafana',
    subreddit: 'grafana',
    devto_tag: 'grafana',
    aliases: [],
    color: '#F46800',
    first_appeared: 2014,
    maintained_by: 'Grafana Labs',
  },
  {
    slug: 'nginx',
    name: 'Nginx',
    description: 'High-performance web server and reverse proxy',
    category: 'devops',
    ecosystem: null,
    website_url: 'https://nginx.org',
    github_repo: 'nginx/nginx',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'nginx',
    subreddit: 'nginx',
    devto_tag: 'nginx',
    aliases: ['engine-x'],
    color: '#009639',
    first_appeared: 2004,
    maintained_by: 'F5 Networks',
  },
  {
    slug: 'pulumi',
    name: 'Pulumi',
    description: 'Infrastructure as code using general-purpose programming languages',
    category: 'devops',
    ecosystem: 'multi',
    website_url: 'https://www.pulumi.com',
    github_repo: 'pulumi/pulumi',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'pulumi',
    subreddit: 'pulumi',
    devto_tag: 'pulumi',
    aliases: [],
    color: '#8A3391',
    first_appeared: 2018,
    maintained_by: 'Pulumi Inc.',
  },

  // ============================================
  // CLOUD & PLATFORMS (10)
  // ============================================
  {
    slug: 'aws',
    name: 'AWS',
    description: 'Amazon Web Services — comprehensive cloud computing platform',
    category: 'cloud',
    ecosystem: null,
    website_url: 'https://aws.amazon.com',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'amazon-web-services',
    subreddit: 'aws',
    devto_tag: 'aws',
    aliases: ['amazon-web-services'],
    color: '#FF9900',
    first_appeared: 2006,
    maintained_by: 'Amazon',
  },
  {
    slug: 'gcp',
    name: 'Google Cloud',
    description: 'Suite of cloud computing services by Google',
    category: 'cloud',
    ecosystem: null,
    website_url: 'https://cloud.google.com',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'google-cloud-platform',
    subreddit: 'googlecloud',
    devto_tag: 'googlecloud',
    aliases: ['google-cloud', 'gcloud'],
    color: '#4285F4',
    first_appeared: 2008,
    maintained_by: 'Google',
  },
  {
    slug: 'azure',
    name: 'Azure',
    description: 'Microsoft cloud computing platform and services',
    category: 'cloud',
    ecosystem: null,
    website_url: 'https://azure.microsoft.com',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'azure',
    subreddit: 'AZURE',
    devto_tag: 'azure',
    aliases: ['microsoft-azure'],
    color: '#0078D4',
    first_appeared: 2010,
    maintained_by: 'Microsoft',
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    description: 'Platform for frontend frameworks and static sites',
    category: 'cloud',
    ecosystem: 'javascript',
    website_url: 'https://vercel.com',
    github_repo: 'vercel/vercel',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'vercel',
    subreddit: 'vercel',
    devto_tag: 'vercel',
    aliases: ['zeit', 'now'],
    color: '#AAAAAA',
    first_appeared: 2015,
    maintained_by: 'Vercel Inc.',
  },
  {
    slug: 'netlify',
    name: 'Netlify',
    description: 'Platform for modern web projects with serverless functions',
    category: 'cloud',
    ecosystem: null,
    website_url: 'https://www.netlify.com',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'netlify',
    subreddit: 'netlify',
    devto_tag: 'netlify',
    aliases: [],
    color: '#00C7B7',
    first_appeared: 2015,
    maintained_by: 'Netlify Inc.',
  },
  {
    slug: 'cloudflare-workers',
    name: 'Cloudflare Workers',
    description: 'Serverless execution environment on Cloudflare edge network',
    category: 'cloud',
    ecosystem: 'javascript',
    website_url: 'https://workers.cloudflare.com',
    github_repo: 'cloudflare/workers-sdk',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'cloudflare-workers',
    subreddit: 'CloudFlare',
    devto_tag: 'cloudflare',
    aliases: ['cf-workers', 'cloudflare'],
    color: '#F38020',
    first_appeared: 2017,
    maintained_by: 'Cloudflare',
  },
  {
    slug: 'fly-io',
    name: 'Fly.io',
    description: 'Platform for running full-stack apps close to users globally',
    category: 'cloud',
    ecosystem: null,
    website_url: 'https://fly.io',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'flyio',
    subreddit: 'flyio',
    devto_tag: 'flyio',
    aliases: ['flyio'],
    color: '#7B3BE2',
    first_appeared: 2017,
    maintained_by: 'Fly.io',
  },
  {
    slug: 'railway',
    name: 'Railway',
    description: 'Infrastructure platform for deploying apps with zero config',
    category: 'cloud',
    ecosystem: null,
    website_url: 'https://railway.app',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'railway',
    subreddit: 'railway',
    devto_tag: 'railway',
    aliases: [],
    color: '#B844FB',
    first_appeared: 2020,
    maintained_by: 'Railway Corp.',
  },
  {
    slug: 'render',
    name: 'Render',
    description: 'Cloud platform for hosting apps, databases, and static sites',
    category: 'cloud',
    ecosystem: null,
    website_url: 'https://render.com',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'render',
    subreddit: 'render',
    devto_tag: 'render',
    aliases: [],
    color: '#46E3B7',
    first_appeared: 2019,
    maintained_by: 'Render Inc.',
  },
  {
    slug: 'digitalocean',
    name: 'DigitalOcean',
    description: 'Cloud infrastructure provider for developers',
    category: 'cloud',
    ecosystem: null,
    website_url: 'https://www.digitalocean.com',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'digitalocean',
    subreddit: 'digital_ocean',
    devto_tag: 'digitalocean',
    aliases: ['do'],
    color: '#0080FF',
    first_appeared: 2011,
    maintained_by: 'DigitalOcean',
  },

  // ============================================
  // MOBILE (8)
  // ============================================
  {
    slug: 'react-native',
    name: 'React Native',
    description: 'Framework for building native mobile apps using React',
    category: 'mobile',
    ecosystem: 'javascript',
    website_url: 'https://reactnative.dev',
    github_repo: 'facebook/react-native',
    npm_package: 'react-native',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'react-native',
    subreddit: 'reactnative',
    devto_tag: 'reactnative',
    aliases: ['rn'],
    color: '#61DAFB',
    first_appeared: 2015,
    maintained_by: 'Meta',
  },
  {
    slug: 'flutter',
    name: 'Flutter',
    description: 'UI toolkit for building natively compiled multiplatform apps',
    category: 'mobile',
    ecosystem: 'dart',
    website_url: 'https://flutter.dev',
    github_repo: 'flutter/flutter',
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'flutter',
    subreddit: 'FlutterDev',
    devto_tag: 'flutter',
    aliases: [],
    color: '#02569B',
    first_appeared: 2017,
    maintained_by: 'Google',
  },
  {
    slug: 'swiftui',
    name: 'SwiftUI',
    description: 'Declarative UI framework for Apple platforms',
    category: 'mobile',
    ecosystem: null,
    website_url: 'https://developer.apple.com/xcode/swiftui/',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'swiftui',
    subreddit: 'SwiftUI',
    devto_tag: 'swiftui',
    aliases: [],
    color: '#F05138',
    first_appeared: 2019,
    maintained_by: 'Apple',
  },
  {
    slug: 'jetpack-compose',
    name: 'Jetpack Compose',
    description: 'Modern declarative UI toolkit for Android',
    category: 'mobile',
    ecosystem: 'java',
    website_url: 'https://developer.android.com/compose',
    github_repo: null,
    npm_package: null,
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'jetpack-compose',
    subreddit: 'JetpackCompose',
    devto_tag: 'jetpackcompose',
    aliases: ['compose'],
    color: '#4285F4',
    first_appeared: 2020,
    maintained_by: 'Google',
  },
  {
    slug: 'expo',
    name: 'Expo',
    description: 'Platform for making universal React Native apps',
    category: 'mobile',
    ecosystem: 'javascript',
    website_url: 'https://expo.dev',
    github_repo: 'expo/expo',
    npm_package: 'expo',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'expo',
    subreddit: 'expo',
    devto_tag: 'expo',
    aliases: [],
    color: '#AAAAAA',
    first_appeared: 2015,
    maintained_by: 'Expo Inc.',
  },
  {
    slug: 'capacitor',
    name: 'Capacitor',
    description: 'Cross-platform native runtime for web apps',
    category: 'mobile',
    ecosystem: 'javascript',
    website_url: 'https://capacitorjs.com',
    github_repo: 'ionic-team/capacitor',
    npm_package: '@capacitor/core',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'capacitor',
    subreddit: null,
    devto_tag: 'capacitor',
    aliases: ['ionic-capacitor'],
    color: '#53B9FF',
    first_appeared: 2019,
    maintained_by: 'Ionic',
  },
  {
    slug: 'tauri',
    name: 'Tauri',
    description: 'Framework for building lightweight desktop apps with web tech',
    category: 'mobile',
    ecosystem: 'rust',
    website_url: 'https://tauri.app',
    github_repo: 'tauri-apps/tauri',
    npm_package: '@tauri-apps/api',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'tauri',
    subreddit: 'tauri',
    devto_tag: 'tauri',
    aliases: [],
    color: '#FFC131',
    first_appeared: 2019,
    maintained_by: 'Tauri Foundation',
  },
  {
    slug: 'electron',
    name: 'Electron',
    description: 'Framework for building cross-platform desktop apps with JavaScript',
    category: 'mobile',
    ecosystem: 'javascript',
    website_url: 'https://www.electronjs.org',
    github_repo: 'electron/electron',
    npm_package: 'electron',
    pypi_package: null,
    crates_package: null,
    stackoverflow_tag: 'electron',
    subreddit: 'electronjs',
    devto_tag: 'electron',
    aliases: ['electronjs'],
    color: '#47848F',
    first_appeared: 2013,
    maintained_by: 'OpenJS Foundation',
  },

  // ============================================
  // AI/ML (7)
  // ============================================
  {
    slug: 'tensorflow',
    name: 'TensorFlow',
    description: 'Open-source platform for machine learning',
    category: 'ai_ml',
    ecosystem: 'python',
    website_url: 'https://www.tensorflow.org',
    github_repo: 'tensorflow/tensorflow',
    npm_package: null,
    pypi_package: 'tensorflow',
    crates_package: null,
    stackoverflow_tag: 'tensorflow',
    subreddit: 'tensorflow',
    devto_tag: 'tensorflow',
    aliases: ['tf'],
    color: '#FF6F00',
    first_appeared: 2015,
    maintained_by: 'Google',
  },
  {
    slug: 'pytorch',
    name: 'PyTorch',
    description: 'Open-source deep learning framework',
    category: 'ai_ml',
    ecosystem: 'python',
    website_url: 'https://pytorch.org',
    github_repo: 'pytorch/pytorch',
    npm_package: null,
    pypi_package: 'torch',
    crates_package: null,
    stackoverflow_tag: 'pytorch',
    subreddit: 'pytorch',
    devto_tag: 'pytorch',
    aliases: ['torch'],
    color: '#EE4C2C',
    first_appeared: 2016,
    maintained_by: 'Meta',
  },
  {
    slug: 'langchain',
    name: 'LangChain',
    description: 'Framework for developing LLM-powered applications',
    category: 'ai_ml',
    ecosystem: 'python',
    website_url: 'https://www.langchain.com',
    github_repo: 'langchain-ai/langchain',
    npm_package: 'langchain',
    pypi_package: 'langchain',
    crates_package: null,
    stackoverflow_tag: 'langchain',
    subreddit: 'LangChain',
    devto_tag: 'langchain',
    aliases: [],
    color: '#3FA878',
    first_appeared: 2022,
    maintained_by: 'LangChain Inc.',
  },
  {
    slug: 'huggingface',
    name: 'Hugging Face',
    description: 'Platform for building and sharing ML models',
    category: 'ai_ml',
    ecosystem: 'python',
    website_url: 'https://huggingface.co',
    github_repo: 'huggingface/transformers',
    npm_package: null,
    pypi_package: 'transformers',
    crates_package: null,
    stackoverflow_tag: 'huggingface-transformers',
    subreddit: null,
    devto_tag: 'huggingface',
    aliases: ['hf', 'transformers'],
    color: '#FFD21E',
    first_appeared: 2018,
    maintained_by: 'Hugging Face Inc.',
  },
  {
    slug: 'openai-api',
    name: 'OpenAI API',
    description: 'API for accessing GPT and other AI models',
    category: 'ai_ml',
    ecosystem: 'multi',
    website_url: 'https://platform.openai.com',
    github_repo: 'openai/openai-python',
    npm_package: 'openai',
    pypi_package: 'openai',
    crates_package: null,
    stackoverflow_tag: 'openai-api',
    subreddit: 'OpenAI',
    devto_tag: 'openai',
    aliases: ['chatgpt', 'gpt'],
    color: '#412991',
    first_appeared: 2020,
    maintained_by: 'OpenAI',
  },
  {
    slug: 'ollama',
    name: 'Ollama',
    description: 'Run large language models locally',
    category: 'ai_ml',
    ecosystem: 'multi',
    website_url: 'https://ollama.com',
    github_repo: 'ollama/ollama',
    npm_package: 'ollama',
    pypi_package: 'ollama',
    crates_package: null,
    stackoverflow_tag: 'ollama',
    subreddit: 'ollama',
    devto_tag: 'ollama',
    aliases: [],
    color: '#888888',
    first_appeared: 2023,
    maintained_by: 'Ollama Inc.',
  },
  {
    slug: 'scikit-learn',
    name: 'scikit-learn',
    description: 'Machine learning library for Python',
    category: 'ai_ml',
    ecosystem: 'python',
    website_url: 'https://scikit-learn.org',
    github_repo: 'scikit-learn/scikit-learn',
    npm_package: null,
    pypi_package: 'scikit-learn',
    crates_package: null,
    stackoverflow_tag: 'scikit-learn',
    subreddit: null,
    devto_tag: 'scikitlearn',
    aliases: ['sklearn'],
    color: '#F7931E',
    first_appeared: 2007,
    maintained_by: 'Community',
  },
]
