/**
 * Tech insight generator — per-technology AI analysis.
 *
 * Replaces template-based insights with genuinely analytical,
 * data-grounded narratives generated by LLM.
 */

import type { AIProvider, GenerateOptions } from '@/lib/ai/provider'
import type { MomentumAnalysis } from '@/lib/scoring/enhanced-momentum'
import type { ConfidenceBreakdown } from '@/lib/scoring/confidence'
import type { SupabaseClient } from '@supabase/supabase-js'
import { getActivePrompt } from '@/lib/ai/prompt-manager'
import {
  buildPromptWithinBudget,
  BUDGETS,
  truncatePeers,
  truncateAnomalies,
  truncateHistory,
} from '@/lib/ai/token-budget'
import type { PromptSection } from '@/lib/ai/token-budget'

// ---- Types ----

export interface TechInsightContext {
  name: string
  slug: string
  category: string
  description: string
  compositeScore: number
  subScores: {
    github: number | null
    community: number | null
    jobs: number | null
    ecosystem: number | null
  }
  momentum: MomentumAnalysis
  confidence: ConfidenceBreakdown
  signals: {
    githubStars: number | null
    githubForks: number | null
    githubContributors: number | null
    hnMentions: number | null
    hnSentiment: number | null
    hnTopStories: Array<{ title: string; points: number }>
    redditPosts: number | null
    devtoArticles: number | null
    jobPostings: {
      adzuna: number | null
      jsearch: number | null
      remotive: number | null
    }
    downloads: { weekly: number | null; trend: number | null }
    soQuestions: number | null
  }
  categoryPeers: Array<{ name: string; score: number; momentum: number }>
  categoryRank: number
  categoryTotal: number
  percentile: number
  anomalies: Array<{
    severity: string
    type: string
    source: string
    metric: string
    deviationSigma: number
    detectedAt: string
    relatedHeadlines: string[]
  }>
  relatedTechs: Array<{
    name: string
    relationship: string
    score: number
  }>
  scoreHistory: Array<{ date: string; score: number }>
  allTimeHigh: number
  allTimeLow: number
}

export interface TechInsight {
  headline: string
  learningPriority: 'critical' | 'high' | 'medium' | 'low' | 'skip'
  trendNarrative: string
  careerAdvice: string
  riskFactors: string
  scoreExplanation: string
  momentumContext: string
  lifecycleStage: string
  confidenceNote: string
  lastUpdated: string
}

// ---- Generator ----

export async function generateTechInsight(
  context: TechInsightContext,
  provider: AIProvider,
  supabase: SupabaseClient
): Promise<TechInsight> {
  const prompt = buildTechPrompt(context)

  // Load system prompt from database
  const systemPrompt = await getActivePrompt(supabase, 'analyst-system')

  const options: GenerateOptions = {
    systemPrompt: systemPrompt || undefined,
    temperature: 0.3,
    maxTokens: 2048,
  }

  return provider.generateJSON<TechInsight>(prompt, undefined, options)
}

// ---- Prompt builder ----

function buildTechPrompt(ctx: TechInsightContext): string {
  const peers = truncatePeers(ctx.categoryPeers)
  const anomalies = truncateAnomalies(ctx.anomalies)
  const history = truncateHistory(ctx.scoreHistory)

  const jobTotal = [
    ctx.signals.jobPostings.adzuna,
    ctx.signals.jobPostings.jsearch,
    ctx.signals.jobPostings.remotive,
  ]
    .filter((v): v is number => v !== null)
    .reduce((a, b) => a + b, 0)

  const sections: PromptSection[] = [
    {
      key: 'instruction',
      priority: 1,
      content: `Analyze this technology and generate a TechInsight JSON with these fields: headline, learningPriority (critical/high/medium/low/skip), trendNarrative, careerAdvice, riskFactors, scoreExplanation, momentumContext, lifecycleStage, confidenceNote, lastUpdated.`,
    },
    {
      key: 'identity',
      priority: 1,
      content: `TECHNOLOGY: ${ctx.name} (${ctx.category})
DESCRIPTION: ${ctx.description}

COMPOSITE SCORE: ${ctx.compositeScore}/100 (all-time high: ${ctx.allTimeHigh}, low: ${ctx.allTimeLow})
CATEGORY RANK: #${ctx.categoryRank} of ${ctx.categoryTotal} in ${ctx.category} (${ctx.percentile}th percentile)
DATA CONFIDENCE: ${ctx.confidence.grade} (${Math.round(ctx.confidence.overall)}%) — ${ctx.confidence.sourceCoverage}% source coverage`,
    },
    {
      key: 'sub_scores',
      priority: 1,
      content: `SUB-SCORES:
- GitHub Activity: ${ctx.subScores.github ?? 'no data'}/100
- Community Buzz: ${ctx.subScores.community ?? 'no data'}/100
- Job Market: ${ctx.subScores.jobs ?? 'no data'}/100
- Ecosystem Health: ${ctx.subScores.ecosystem ?? 'no data'}/100`,
    },
    {
      key: 'momentum',
      priority: 1,
      content: `MOMENTUM:
- 7-day: ${ctx.momentum.shortTerm > 0 ? '+' : ''}${ctx.momentum.shortTerm.toFixed(2)}
- 30-day: ${ctx.momentum.mediumTerm > 0 ? '+' : ''}${ctx.momentum.mediumTerm.toFixed(2)}
- 90-day: ${ctx.momentum.longTerm > 0 ? '+' : ''}${ctx.momentum.longTerm.toFixed(2)}
- Trajectory: ${ctx.momentum.trend}
- Acceleration: ${ctx.momentum.acceleration > 0 ? '+' : ''}${ctx.momentum.acceleration.toFixed(2)}
- Volatility: ${ctx.momentum.volatility.toFixed(2)}
- Direction streak: ${ctx.momentum.streak} days`,
    },
    {
      key: 'signals',
      priority: 2,
      content: `RAW SIGNALS:
- GitHub: ${ctx.signals.githubStars?.toLocaleString() ?? 'N/A'} stars, ${ctx.signals.githubForks?.toLocaleString() ?? 'N/A'} forks
- Hacker News: ${ctx.signals.hnMentions ?? 'N/A'} mentions (30d), sentiment ${ctx.signals.hnSentiment != null ? (ctx.signals.hnSentiment * 100).toFixed(0) + '%' : 'N/A'}
${ctx.signals.hnTopStories.length > 0 ? '- Top HN: ' + ctx.signals.hnTopStories.slice(0, 3).map((s) => `"${s.title}" (${s.points}pts)`).join(', ') : ''}
- Reddit: ${ctx.signals.redditPosts ?? 'N/A'} posts (30d)
- Dev.to: ${ctx.signals.devtoArticles ?? 'N/A'} articles (30d)
- Jobs: ${jobTotal > 0 ? jobTotal.toLocaleString() : 'N/A'} total postings
- Downloads: ${ctx.signals.downloads.weekly?.toLocaleString() ?? 'N/A'}/week (trend: ${ctx.signals.downloads.trend != null ? (ctx.signals.downloads.trend > 0 ? '+' : '') + ctx.signals.downloads.trend.toFixed(1) + '%' : 'N/A'})
- Stack Overflow: ${ctx.signals.soQuestions?.toLocaleString() ?? 'N/A'} questions`,
    },
    {
      key: 'peers',
      priority: 2,
      content: `PEERS IN ${ctx.category.toUpperCase()}:
${peers.map((p) => `- ${p.name}: ${p.score}/100 (momentum ${p.momentum > 0 ? '+' : ''}${p.momentum.toFixed(1)})`).join('\n')}`,
    },
    {
      key: 'anomalies',
      priority: 2,
      content:
        anomalies.length > 0
          ? `ANOMALIES DETECTED:\n${anomalies.map((a) => `- ${a.severity.toUpperCase()}: ${a.type} in ${a.source}/${a.metric} (${a.deviationSigma.toFixed(1)}σ deviation)${a.relatedHeadlines.length > 0 ? ` — possibly related to: "${a.relatedHeadlines[0]}"` : ''}`).join('\n')}`
          : 'NO ANOMALIES DETECTED',
    },
    {
      key: 'related',
      priority: 3,
      content:
        ctx.relatedTechs.length > 0
          ? `RELATED TECHNOLOGIES:\n${ctx.relatedTechs.map((r) => `- ${r.name} (${r.relationship}): score ${r.score}`).join('\n')}`
          : '',
    },
    {
      key: 'history',
      priority: 3,
      content:
        history.length > 0
          ? `SCORE HISTORY (last ${history.length} days):\n${history.map((h) => `${h.date}: ${h.score}`).join(', ')}`
          : '',
    },
  ]

  return (
    buildPromptWithinBudget(
      sections.filter((s) => s.content.length > 0),
      BUDGETS.techInsight
    ) + '\n\nGenerate the TechInsight JSON.'
  )
}
